<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-05-06T00:39:30 IST" name="Suite" finished-at="2024-05-06T00:39:41 IST" duration-ms="11098">
    <groups>
    </groups>
    <test started-at="2024-05-06T00:39:30 IST" name="TestFour" finished-at="2024-05-06T00:39:41 IST" duration-ms="10408">
      <class name="tests.FourTest">
        <test-method signature="testFour()[pri:0, instance:tests.FourTest@1a5b6f42]" started-at="2024-05-06T00:39:30 IST" name="testFour" finished-at="2024-05-06T00:39:40 IST" duration-ms="9327" status="FAIL">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at tests.FourTest.testFour(FourTest.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFour -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.FourTest@1a5b6f42]" started-at="2024-05-06T00:39:40 IST" name="tearDown" finished-at="2024-05-06T00:39:41 IST" duration-ms="582" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.FourTest -->
    </test> <!-- TestFour -->
    <test started-at="2024-05-06T00:39:30 IST" name="TestThree" finished-at="2024-05-06T00:39:40 IST" duration-ms="9400">
      <class name="tests.ThreeTest">
        <test-method signature="testThree()[pri:0, instance:tests.ThreeTest@205d38da]" started-at="2024-05-06T00:39:30 IST" name="testThree" finished-at="2024-05-06T00:39:40 IST" duration-ms="9315" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testThree -->
      </class> <!-- tests.ThreeTest -->
    </test> <!-- TestThree -->
    <test started-at="2024-05-06T00:39:30 IST" name="TestTwo" finished-at="2024-05-06T00:39:40 IST" duration-ms="10185">
      <class name="tests.TwoTest">
        <test-method signature="testTwo()[pri:0, instance:tests.TwoTest@2663e964]" started-at="2024-05-06T00:39:30 IST" name="testTwo" finished-at="2024-05-06T00:39:40 IST" duration-ms="10123" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTwo -->
      </class> <!-- tests.TwoTest -->
    </test> <!-- TestTwo -->
    <test started-at="2024-05-06T00:39:30 IST" name="TestLogin" finished-at="2024-05-06T00:39:41 IST" duration-ms="11098">
      <class name="tests.LoginTest">
        <test-method is-config="true" signature="openApplication()[pri:0, instance:tests.LoginTest@5f0fd5a0]" started-at="2024-05-06T00:39:30 IST" name="openApplication" finished-at="2024-05-06T00:39:38 IST" duration-ms="8182" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method signature="login(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:tests.LoginTest@5f0fd5a0]" started-at="2024-05-06T00:39:38 IST" name="login" data-provider="getLoginData" finished-at="2024-05-06T00:39:41 IST" duration-ms="2441" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[anirudha.selenium5@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Anirudha@123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Successfull]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.LoginTest@5f0fd5a0]" started-at="2024-05-06T00:39:41 IST" name="tearDown" finished-at="2024-05-06T00:39:41 IST" duration-ms="411" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.LoginTest -->
    </test> <!-- TestLogin -->
  </suite> <!-- Suite -->
</testng-results>
